EnergyManufacture/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('LineDetection.urls', namespace = 'LineDetection'))
]

LineDetection/urls.py
from django.urls import path, re_path

from . import views

app_name = 'LineDetection'
urlpatterns = [
    path(r'', views.login_index, name='login_index'),
    path('login', views.login_index, name='login'),
    path('index/<int:character>/', views.index, name='index'),
    path('monitor_index/<int:character>/', views.monitor_index, name='monitor_index'),
    path('report/<int:character>/', views.report, name='report'),
    path('monitor/<int:facility_id>/<int:character>/', views.monitor, name='monitor'),
    path('exclude_anomaly/<int:facility_id>/<int:character>/', views.exclude_anomaly, name='exclude_anomaly'),
    path('statistics/<int:facility_id>/<int:character>/',views.statistics, name='statistics'),
    path('cluster/<int:facility_id>/<int:character>/',views.cluster, name='cluster'),
    path('cluster_superuser/<int:facility_id>/<int:character>/',views.cluster_superuser, name='cluster_superuser'),
    path('cluster_superuser_view_article/<int:article_id>',views.cluster_superuser_view_article, name='cluster_superuser_view_article'),
    path('calender/<int:facility_id>/<int:character>/',views.calender, name='calender'),
    path('setcluster/<int:facility_id>/<int:cluster_number>/<int:character>/',views.setcluster, name='setcluster'),
    path('login_action',views.login_action, name='login_action'),
    path('fix_anomaly_action/<int:facility_id>/<int:anomaly_id>/<int:character>/',views.fix_anomaly_action, name='fix_anomaly_action'),
#    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
#    path('<int:question_id>/vote/', views.vote, name='vote'),
]

LineDetection/models.py
from django.db import models
from django_pandas.managers import DataFrameManager

# Create your models here.


class Facility(models.Model):
    facility_name = models.CharField(max_length=200)
    production_line = models.IntegerField(default=0)
    brand = models.CharField(max_length=20)
    install_date = models.DateTimeField('installed date')
    energy_total = models.FloatField(default = 0)
    objects = DataFrameManager()

    def __str__(self):
        return self.facility_name

class Energy(models.Model):
    facility = models.ForeignKey(Facility, on_delete=models.CASCADE)
    season = models.IntegerField(default=0)
    energy_date = models.DateTimeField('energy date')
    energy = models.FloatField(default = 0)
    objects = DataFrameManager()

class Anomaly(models.Model):
    facility = models.ForeignKey(Facility, on_delete=models.CASCADE)
    season = models.IntegerField(default=0)
    anomaly_date = models.DateTimeField('energy date')
    anomaly_type = models.IntegerField(default=0)
    anomaly_comments = models.CharField(max_length=200)
    anomaly_solve = models.IntegerField(default=0)
    solved_comments = models.CharField(max_length=200, default = '', null = True)
    objects = DataFrameManager()

class season_goal(models.Model):
    season = models.IntegerField(default=0)
    production_line = models.IntegerField(default=0)
    goal = models.IntegerField(default=0)
    objects = DataFrameManager()

class production_amount(models.Model):
    season = models.ForeignKey(season_goal, on_delete=models.CASCADE)
    production_date = models.DateTimeField('pruduction date')
    production_line = models.IntegerField(default=0)
    amount = models.IntegerField(default=0)
    objects = DataFrameManager()

class Cluster(models.Model):
    facility = models.ForeignKey(Facility, on_delete=models.CASCADE)
    cluster_id = models.IntegerField(default=0)
    anomaly_condition = models.IntegerField(default=0)
    anomaly_comments = models.CharField(max_length=200, default = '', null=True)
    #position = models.IntegerField(default=0)
    #energy = models.FloatField(default = 0)
    #season = models.IntegerField(default=0, null=True)
    objects = DataFrameManager()

class Tag(models.Model):
    tag_text = models.CharField(max_length=200, default = '', null=True)
    facility_id = models.ForeignKey(Facility, on_delete=models.CASCADE, null=True)
    objects = DataFrameManager()

    def __str__(self):
        return self.tag_text

    class Meta: 
        verbose_name='标签'
        verbose_name_plural='标签'

class Article(models.Model):
    article_name = models.CharField(max_length=200, default = '', null=True)
    article = models.CharField(max_length=2000, default = '', null=True)
    tag_on = models.ManyToManyField(Tag, blank=True)
    pub_date = models.DateTimeField('article date')
    objects = DataFrameManager()

    def __str__(self):
        return self.article_name
    
    class Meta: 
        verbose_name='文章'
        verbose_name_plural='文章'

    def get_article_name(self):
        return self.article_name
    
    def get_pub_date(self):
        return self.pub_date
    
    get_article_name.short_description = r'文章名称'
    get_pub_date.short_description = r'发布时间'

LineDetection/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from itertools import chain
from .models import Facility, Energy, Anomaly, Cluster, season_goal, production_amount, Tag, Article
from .utils import *
import pandas as pd
import json
import numpy as np
import calendar
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, silhouette_samples
import datetime

# Create your views here.

def login_index(request):
    return render(request, 'LineDetection/login.html')

def login_action(request):
    character_num = -1
    if request.method=="GET":
        account=request.GET.get('account',None)
        password=request.GET.get('password',None)
        character=request.GET.get('character',None)
        if(character=='能耗分析人员'):
            character_num = 0
        elif(character=='普通用户'):
            character_num = 1
        else:
            character_num = 2
    return HttpResponseRedirect(reverse('LineDetection:index', args=(character_num,)))

def index(request,character):
    return render(request, 'LineDetection/index.html', {'character': character})

def monitor_index(request,character):
    sql = open('SQL/index.sql', 'r')
    sql_query = sql.read()
    sql_query = sql_query.replace('\n',' ')
    queryset = Anomaly.objects.raw(sql_query)
    return render(request, 'LineDetection/yxjc.html', {'facility_list': queryset,'character':character})

def report(request,character):
    return render(request, 'LineDetection/report.html',{'character':character})

def monitor(request, facility_id, character):
    sql = open('SQL/monitor.sql', 'r')
    sql_query = sql.read()
    sql_query = sql_query.replace('\n',' ').replace('###', str(facility_id))
    queryset = Anomaly.objects.raw(sql_query)[:10]

    five_day_energy = Energy.objects.filter(facility_id = facility_id)
    five_day_energy_df = five_day_energy.to_dataframe()
    #five_day_energy_df.to_csv('test.csv', index=False)
    five_day_energy_df['date'] = pd.to_datetime(five_day_energy_df.energy_date,format="%Y/%m/%d")
    five_day_energy_df['hour'] = five_day_energy_df['date'].dt.hour
    aggregation = {'hour':'first','energy':'sum'}
    five_day_energy_group = five_day_energy_df.groupby('hour').agg(aggregation)
    five_day_energy_group = five_day_energy_group.sort_values("hour",inplace=False)
    #five_day_energy_group.to_csv('test.csv')
    five_day_energy_group = five_day_energy_group.reset_index(drop=True)
    five_day_energy_list = [{
        'hour':five_day_energy_group['hour'].tolist()[-5:],
        'energy':five_day_energy_group['energy'].tolist()[-5:]
    }]
    five_day_energy_json = json.dumps(five_day_energy_list)

    energy_limit = Facility.objects.filter(id = facility_id)
    energy_limit = energy_limit.to_dataframe()['energy_total'].tolist()[0]
    return render(request, 'LineDetection/monitor.html', \
        {'energy_list': queryset, 'five_day_energy': five_day_energy_json, 'facility_id': facility_id, \
            'latest_energy': round(five_day_energy_group['energy'].tolist()[-1],0), 'energy_limit': energy_limit,'character':character})

def statistics(request, facility_id,character):
    production = production_amount.objects.all().to_dataframe()
    production['season_id'] = production['season'].str[-2]
    production['season_id'] = production['season_id'].astype(int)
    #production.to_csv('test.csv')
    season = season_goal.objects.all().to_dataframe()
    #season.to_csv('test2.csv')
    prod = pd.merge(production, season, how = 'left', left_on = 'season_id', right_on = 'id')
    prod = prod.sort_index(by='production_date').reset_index(drop=True)
    prod['date'] = pd.to_datetime(prod.production_date,format="%Y/%m/%d")
    prod['day'] = prod['date'].dt.day
    prod['month'] = prod['date'].dt.month
    prod['year'] = prod['date'].dt.year
    total_time = calendar.monthrange(prod['year'].tolist()[-1], prod['month'].tolist()[-1])[1]
    passed_time = prod['day'].tolist()[-1]
    time_json = [{
        'total':total_time,
        'passed':passed_time
    }]

    aggregation_amount = {'goal':'first','amount':'sum'}
    prod_amount = prod.groupby('season_id').agg(aggregation_amount)
    goal = prod_amount['goal'].tolist()[0]
    done_amount = prod_amount['amount'].tolist()[0]
    left_amount = goal - done_amount
    prod_json = [{
        'total':goal,
        'done':done_amount
    }]

    anomaly = Anomaly.objects.filter(facility_id = facility_id)
    anomaly_df = anomaly.to_dataframe()
    anomaly_df['date'] = pd.to_datetime(anomaly_df.anomaly_date,format="%YYYY/%MM/%DD")
    anomaly_df = anomaly_df.sort_values("date",inplace=False).reset_index(drop=True)
    anomaly_df['compare_date'] = anomaly_df.apply(lambda df: get_compare_date(df), axis = 1)


    anomaly_df['1_flag'] = anomaly_df.apply(lambda df: get_type_num(df, str(1)), axis = 1)
    anomaly_df['2_flag'] = anomaly_df.apply(lambda df: get_type_num(df, str(2)), axis = 1)
    anomaly_df['3_flag'] = anomaly_df.apply(lambda df: get_type_num(df, str(3)), axis = 1)
    anomaly_df['4_flag'] = anomaly_df.apply(lambda df: get_type_num(df, str(4)), axis = 1)

    anomaly_pivot = pd.pivot_table(anomaly_df,index=["compare_date"],values=["1_flag","2_flag","3_flag","4_flag"],\
                                    aggfunc=np.count_nonzero)
    anomaly_bar_json = [{
        'compare_date':list(anomaly_pivot.index),
        'data_1':anomaly_pivot['1_flag'].tolist(),
        'data_2':anomaly_pivot['2_flag'].tolist(),
        'data_3':anomaly_pivot['3_flag'].tolist(),
        'data_4':anomaly_pivot['4_flag'].tolist()
    }]

    anomaly_pie_json = [{
        'data_1':np.sum(anomaly_pivot['1_flag'].tolist()),
        'data_2':np.sum(anomaly_pivot['2_flag'].tolist()),
        'data_3':np.sum(anomaly_pivot['3_flag'].tolist()),
        'data_4':np.sum(anomaly_pivot['4_flag'].tolist())
    }]
    return render(request, 'LineDetection/statistics.html', {'prod':prod_json,'time': time_json,'facility_id': facility_id, 'anomaly_bar': anomaly_bar_json,\
                  'anomaly_pie': anomaly_pie_json,'goal':goal, 'done_amount':done_amount, 'total_time':total_time,'passed_time':passed_time,\
                  'left_amount':left_amount,'character':character}) 

def cluster(request, facility_id,character):
    #total_energy = Energy.objects.filter(facility_id = facility_id)
    #total_energy = Energy.objects.values('energy','energy_date').all()
    #total_energy = total_energy.to_dataframe()
    total_energy = pd.read_csv('total_energy.csv')
    total_energy_list = total_energy['energy'].tolist()
    total_date_list = total_energy['energy_date'].tolist()
    kmeans_energy = []
    kmeans_date = []
    for i in range(200):
        temp_list = total_energy_list[1000*i:1000*i+1000]
        kmeans_energy.append(temp_list)
    for i in range(200):
        temp_list = [0,0]
        temp_list[0] = total_date_list[1000*i]
        temp_list[1] = total_date_list[1000*i+1000-1]
        kmeans_date.append(temp_list)
    score = 0
    cluster = 2
    for i in range(2,20):
        k_means = KMeans(n_clusters=i, random_state=10)
        y_predict = k_means.fit_predict(kmeans_energy)
        s = silhouette_score(kmeans_energy, y_predict)
        if(score<s):
            score = s
            cluster = i
    k_means = KMeans(n_clusters=cluster, random_state=10)
    y_predict = k_means.fit_predict(kmeans_energy)
    center=k_means.cluster_centers_
    labels=k_means.labels_
    json_cluster = []
    for i in range(cluster):
        temp_cluster = {}
        cluster_name = 'cluster_' + str(i)
        temp_cluster['name'] = cluster_name
        temp_cluster['xdata'] = [i for i in range(len(list(center[i])))]
        temp_cluster['ydata'] = list(center[i])
        temp_cluster['type'] = 'line'
        json_cluster.append(temp_cluster)
    
    cluster_info = Cluster.objects.all()
    return render(request, 'LineDetection/cluster.html', {'json_cluster':json.dumps(json_cluster),'facility_id':facility_id,\
                                                           'cluster_info':cluster_info,'character':character})

def calender(request, facility_id,character):
    total_energy = pd.read_csv('total_energy.csv')
    total_energy['date'] = pd.to_datetime(total_energy.energy_date,format="%Y/%m/%d")
    total_energy['day'] = total_energy['date'].dt.day
    total_energy['month'] = total_energy['date'].dt.month
    total_energy['year'] = total_energy['date'].dt.year
    total_energy['day'] = total_energy['day'].astype(str)
    total_energy['month'] = total_energy['month'].astype(str)
    total_energy['year'] = total_energy['year'].astype(str)
    total_energy['count_day'] = total_energy['year']+"-"+total_energy['month']+"-"+total_energy['day']
    aggregation = {'count_day':'first','energy':'sum'}
    total_energy_group = total_energy.groupby('count_day').agg(aggregation)
    total_energy_group = total_energy_group.sort_values("energy",inplace=False)
    total_energy_group = total_energy_group.reset_index(drop=True)
    
    '''
    # five top energy
    five_top_energy_json = [{
        'row_1_date':total_energy_group.iloc[0].tolist()[0],
        'row_1_energy':total_energy_group.iloc[0][1],
        'row_2_date':total_energy_group.iloc[1][0],
        'row_2_energy':total_energy_group.iloc[1][1],
        'row_3_date':total_energy_group.iloc[2][0],
        'row_3_energy':total_energy_group.iloc[2][1],
        'row_4_date':total_energy_group.iloc[3][0],
        'row_4_energy':total_energy_group.iloc[3][1],
        'row_5_date':total_energy_group.iloc[4][0],
        'row_5_energy':total_energy_group.iloc[4][1]
    }]
    '''
    
    max_energy = total_energy_group.iloc[0].tolist()
    min_energy = total_energy_group.iloc[-1].tolist()
    
    '''
    # get day of a date

LineDetection/templates/LineDetection/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'LineDetection/bootstrap/css/bootstrap.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>汽车涂装工艺能耗异常检测系统</title>

<style>
* {
	padding: 0;
	margin: 0;
}

html,
body {
	width: 100%;
	height: 100%;
}

.cms_login {
	width: 100%;
	height: 100%;
	display: flex;
	justify-content: center;
	background-repeat: no-repeat;
	background-image: url("{% static 'LineDetection/vince/images/login_background.jpeg' %}");
	background-size: 100% 100%;
}

.cms_login_container {
	width: 600px;
	height: 360px;
	border-radius: 10px;
	border: 1px solid #ccc;
	box-shadow: 0px 0px 10px #ccc;
	background-color: #fff;
	margin: auto;
	opacity: 0.8;
}

.cms_login_text {
	height: 100px;
	width: 100%;
	line-height: 80px;
	text-align: center;
	font-size: 30px;
}

.cms_login_table {
	font-size: 18px;
}

/* 统一盒子样式 */
.divBox {
	height: 50px;
	width: 100%;
	line-height: 50px;
	text-align: center;
}

.divBox_select {
	height: 30px;
	width: 48%;
	line-height: 50px;
	text-align: center;
}

.cms_login_ipt {
	height: 30px;
	width: 290px;
	padding-left: 5px;
	border-radius: 5px;
	outline: none;
}

input:focus {
	border-radius: 5px;
	outline: none;
	border: 2px solid #66afe9;
	box-shadow: inset 0 2px 2px rgba(0, 0, 0, .075), 0 0 8px rgba(102, 175, 233, 0.6);
}

.margin_right10 {
	margin-right: 10px;
}

.margin_top30 {
	margin-top: 30px;
}

.margin_top60 {
	margin-top: 60px;
}

.login_btn {
	width: 360px;
	height: 100%;
	background-color: #1360a7;
	border-radius: 10px;
	outline: none;
	font-size: 24px;
	color: white;
	letter-spacing: 24px;
}

.login_btn:hover {
	background-color: #1e5d5d;
}
</style>
</head>

<body>
<div class="cms_login">
<div class="cms_login_container">
	<div class="cms_login_text">汽车涂装工艺能耗异常检测系统</div>
	<div class="cms_login_table">
		<form action="{% url 'LineDetection:login_action' %}">
			{% csrf_token %}
			<div class="divBox"><span class="margin_right10">账号</span><input type="text" placeholder="请输入账号"
					class="cms_login_ipt" name = 'account'></div>
			<div class="divBox"><span class="margin_right10">密码</span><input type="password" placeholder="请输入密码"
					class="cms_login_ipt" name='password'></div>
			<div class="divBox"><span class="margin_right10">角色</span>
				<select class="divBox_select" name='character'>
					<option>能耗分析人员</option>
					<option>普通用户</option>
					<option>现场巡查人员</option>
				</select>
			</div>
			<div class="divBox margin_top30">
				<button class="login_btn">登录</button>
			</div>
		</form>
	</div>
</div>
</div>
</body>

</html>

LineDetection/templates/LineDetection/yxjc.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=10">
    <title>运行监测</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" type="text/css" href="{% static 'LineDetection/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'LineDetection/dist/css/ionicons.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'LineDetection/dist/css/AdminLTE.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'LineDetection/dist/css/skins/all-skins.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'LineDetection/vince/css/vince.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'LineDetection/vince/biao/css/font-awesome.min.css' %}">
    <!--[if lt IE 9]>
    <script src="dist/js/html5shiv.min.js"></script>
    <script src="dist/js/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">   
<div class="wrapper">
    <header class="main-header">
        <a href="#" class="logo">
      <span class="logo-mini">
	  <img src="{% static 'LineDetection/vince/images/v01.png' %}">
	  </span>
           <span class="logo-lg"><img src="{% static 'LineDetection/vince/images/v01.png' %}">汽车制造</span>
        </a>
        <nav class="navbar navbar-static-top">
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button"></a>
            <span class="all_title">汽车涂装工艺能耗异常检测系统</span>
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{% static 'LineDetection/dist/img/user2-160x160.jpg' %}" class="user-image" alt="User Image">
                            {% if character == 0 %}
                                <span class="hidden-xs">能耗分析人员</span>
                            {% endif %}
                            {% if character == 1 %}
                                <span class="hidden-xs">普通用户</span>
                            {% endif %}
                            {% if character == 2 %}
                                <span class="hidden-xs">现场排查人员</span>
                            {% endif %}
                        </a>
                        <ul class="dropdown-menu">
                            <li class="user-header">
                                <img src="{% static 'LineDetection/dist/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image">
                                <p>
                                    姓名：管理员
                                    <small>部门：信息部</small>
                                </p>
                            </li>
                            <li class="user-footer">
                                <div class="pull-right">
                                    <a href="{% url 'LineDetection:login' %}" class="btn btn-default btn-flat">退出系统</a>
                                </div>
                            </li>
                        </ul>
                    </li>

                </ul>
            </div>
        </nav>
    </header>

    <aside class="main-sidebar">
        <section class="sidebar">
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="{% static 'LineDetection/dist/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    {% if character == 0 %}
                        <p>能耗分析人员</p>
                    {% endif %}
                    {% if character == 1 %}
                        <p>普通用户</p>
                    {% endif %}
                    {% if character == 2 %}
                        <p>现场排查人员</p>
                    {% endif %}
                    <p class="menu_time">
                        时间：<span id="nowTime"></span></p>
                </div>
            </div>

            <ul class="sidebar-menu">
                <li class="header">菜单 MENU</li>
                <li>
                    <a href="{% url 'LineDetection:index' character %}">
                        <i class="fa fa-home" style="font-size: 22px"></i> <span>首页</span>
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'LineDetection:monitor_index' character %}">
                        <i class="fa fa-eye"></i> <span>异常检测</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'LineDetection:report' character %}">
                        <i class="fa fa-map"></i> <span>能耗报表</span>
                    </a>
                </li>
                <li class="treeview">
                    <a href="http://127.0.0.1:8000/admin/LineDetection/article/">
                        <i class="fa fa-print"></i>
                        <span>异常检测分享博客</span>
                    </a>
                </li>
            </ul>
        </section>
    </aside>
    <div class="content-wrapper">
        <section class="content-header">
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> 首页</a></li>
                <li class="active">运行监测</li>
            </ol>
        </section>
        <div class="content qqq">
            <div class="yxjc">
                <div class="yxjc_info">
                    <ul>
                        <li class="kong xuanli"><p>一号生产线<span class="yxjc_tubiao1"></span></p></li>
                        <li class="qi"><p>二号生产线<span class="yxjc_tubiao2"></span></p></li>
                        <li class="qi"><p>三号生产线<span class="yxjc_tubiao3"></span></p></li>
                    </ul>
                </div>
                <div class="yxjc_info_right">
                    <img src="{% static 'LineDetection/vince/images/生产线_1.jpg' %}">
                </div>

                <div class="yxjc_info_right">
                    {% if facility_list %}
                        {% for facility in facility_list %}
                            <div class="col-lg-2 yxjc_info_facility">
                                {% if facility.anomaly_type %}
                                <div class="yxpjxg_three">
                                    <p>异常</p>
                                </div>
                                <p><span>工艺:    </span>{{ facility.facility_name }}</p>
                                <p><span>用电量：</span>{{ facility.total_energy }}KW·h</p>
                                <p><span>发生时间： </span>{{ facility.anomaly_date }}</p>
                                <p><span>异常种类：</span>{{ facility.anomaly_type }}</p>
                                <p><span>判断原因：</span>{{ facility.anomaly_comments }}</p>
                                <a href="{% url 'LineDetection:monitor' facility.id character %}">
                                    <button type="button" class="btn btn-success">查看</button>
                                </a>
                                {% else %}
                                <div class="yxpjxg_two">
                                    <p>正常</p>
                                </div>
                                <p><span>工艺:    </span>{{ facility.facility_name }}</p>
                                <p><span>用电量：</span>{{ facility.total_energy }}KW·h</p>
                                <p><span>生产线：</span>{{ facility.production_line }}</p>
                                <p><span>安装时间： </span>{{ facility.install_date }}</p>
                                <p><span>品牌：</span>{{ facility.brand }}</p>
                                <a href="{% url 'LineDetection:monitor' facility.id character %}">
                                        <button type="button" class="btn btn-success">查看</button>
                                </a>
                                {% endif %}
                            </div>
                        {% endfor %}
                    {% else %}
                        <p>No facilities are available.</p>
                    {% endif %}
                </div>
                
                </div>
            </div>
        </div>
    </div>
    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b></b>
        </div>
        <strong>Copyright &copy; All Rights Reserved powered by Shanyue</strong>
    </footer>
    <div class="control-sidebar-bg"></div>
</div>
<script src="{% static 'LineDetection/vince/js/jquery-2.2.3.min.js' %}"></script>
<script src="{% static 'LineDetection/vince/global.js' %}"></script>
<script src="{% static 'LineDetection/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'LineDetection/dist/js/app.min.js' %}"></script>
<script src="{% static 'LineDetection/dist/js/demo.js' %}"></script>
<script src="{% static 'LineDetection/vince/js/nicescroll.js' %}"></script>
<script src="{% static 'LineDetection/vince/js/demo.js' %}"></script>
<div id="sss" style="display:none;height:200px;width:200px;"></div>
<script src="{% static 'LineDetection/vince/js/echarts.min.js' %}"></script>
<script type="text/javascript">
    import * as echarts from "{% static 'LineDetection/vince/js/jquery' %}";

    const myChart1 = echarts.init(document.getElementById('sss'));
    option1 = {
        series: [{data: [247, 179]}]
    };
    myChart1.setOption(option1);
</script>

</body>
</html>